arb-dir: assets/strings
template-arb-file: strings_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/src/shared/presentation/localization
synthetic-package: false
use-escaping: true