name: flutter_mvvm
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.19.0
  json: ^0.20.4
  light_sliver_view:
    git:
      url: https://bitbucket.org/hiberus/mobile-flutter-flutter-components.git
      path: light_sliver_view
      ref: feature/light_sliver_view

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  package_rename: ^1.9.0

flutter:
  uses-material-design: true
  generate: true

  # Project assets
  assets:
    - assets/images/
    - assets/strings/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  # After changing this config, run: dart run flutter_native_splash:create
  color: "#ffffff"
  image: assets/images/splash.png

flutter_launcher_icons:
  # After changing this config, run: dart run flutter_launcher_icons
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

package_rename_config:
  # After changing this config, run: dart run package_rename
  android:
    app_name: "Flutter MVVM"
    package_name: "com.example.flutter_mvvm"

  ios:
    app_name: "Flutter MVVM"
    package_name: "com.example.flutter_mvvm"
